CREATE TABLE goodEntity (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      description TEXT,
                      price NUMERIC(10, 2) NOT NULL
);